import { Code, Layers, PenTool, Database, Brain } from "lucide-react";

export const projects = [
  {
    id: 1,
    title: "AI-Powered Task Manager",
    description: "A smart task management app that uses AI to prioritize and categorize tasks.",
    category: "Web Development",
    icon: Code,
    technologies: ["React", "Node.js", "TensorFlow.js"],
    github: "#",
    live: "#",
  },
  {
    id: 2,
    title: "Eco-Tracker Mobile App",
    description: "An app that helps users track and reduce their carbon footprint.",
    category: "Mobile Development",
    icon: Layers,
    technologies: ["React Native", "Firebase"],
    github: "#",
    live: "#",
  },
  {
    id: 3,
    title: "Virtual Reality Art Gallery",
    description: "A VR experience showcasing digital art in an immersive environment.",
    category: "VR/AR",
    icon: PenTool,
    technologies: ["Unity", "C#", "Blender"],
    github: "#",
    live: "#",
  },
  {
    id: 4,
    title: "Blockchain-based Voting System",
    description: "A secure and transparent voting system using blockchain technology.",
    category: "Blockchain",
    icon: Database,
    technologies: ["Solidity", "Ethereum", "Web3.js"],
    github: "#",
    live: "#",
  },
  {
    id: 5,
    title: "AI Image Generator",
    description: "An AI-powered tool that generates unique images based on text descriptions.",
    category: "AI/ML",
    icon: Brain,
    technologies: ["Python", "PyTorch", "Flask"],
    github: "#",
    live: "#",
  },
];
